#!/usr/bin/env ruby
# xssrays - Example BeEF RESTful API script
# Refer to the wiki for info: https://github.com/beefproject/beef/wiki/BeEF-RESTful-API
##
require 'rest-client'
require 'json'
require 'optparse'
require 'pp'
require './lib/string' # colored strings
require './lib/print'  # print wrappers
require './lib/beef_rest_api'

if ARGV.length == 0
  puts "#{$0}:"
  puts "|  Example BeEF RESTful API script"
  puts "|  Use --help for help"
  puts "|_ Use verbose mode (-v) and debug mode (-d) for more output"
  exit 1
end

# API config
proto = 'http'
host = '127.0.0.1'
port = '3000'
user = 'beef'
pass = 'beef'

# Command line options
@debug = false
@verbose = false
OptionParser.new do |opts|
  opts.on('-h', '--help', 'Shows this help screen') do
    puts opts
    exit 1
  end
  opts.on('--host HOST', "Set BeEF host (default: #{host})") do |h|
    host = h
  end
  opts.on('--port PORT', "Set BeEF port (default: #{port})") do |p|
    port = p
  end
  opts.on('--user USERNAME', "Set BeEF username (default: #{user})") do |u|
    user = u
  end
  opts.on('--pass PASSWORD', "Set BeEF password (default: #{pass})") do |p|
    pass = p
  end
  opts.on('--ssl', 'Use HTTPS') do
    proto = 'https'
  end
  opts.on('-v', '--verbose', 'Enable verbose output') do
    @verbose = true
  end
  opts.on('-d', '--debug', 'Enable debug output') do
    @debug = true
  end
end.parse!

@api = BeefRestAPI.new proto, host, port, user, pass

# Retrieve the RESTful API token
print_status "Authenticating to: #{proto}://#{host}:#{port}"
@api.auth

# Retrieve BeEF version
@api.version

# Retrieve all scans
scans = @api.xssrays_scans_all
print_debug scans

# Retrieve all rays
rays = @api.xssrays_rays_all
print_debug rays

# Retrieve online hooked browser list
hooks = @api.online_browsers.flatten
exit 1 if hooks.empty?
print_debug hooks

# Retrieve rays for each hooked browser
hooks.each do |hook|
  next if hook['id'].nil?
  print_status "Retrieving rays for browser [id: #{hook['id']}]"
  rays = @api.xssrays_rays(hook['session'])
  print_debug rays
  rays['rays'].each do |ray|
    next if ray['id'].nil?
    print_verbose "#{ray['vector_name']} (#{ray['vector_method']})"
  end
end

# Retrieve scans for each hooked browser
hooks.each do |hook|
  next if hook['id'].nil?
  print_status "Retrieving scans for browser [id: #{hook['id']}]"
  scans = @api.xssrays_scans(hook['session'])
  print_debug scans
  scans['scans'].each do |scan|
    next if scan['id'].nil?
    print_verbose "Scan [#{scan['id']}] on domain #{scan['domain']}"
  end
end

